### ISSUE TITLE
less编译报错：[ERROR] parser.less: Unable to perform comparison

### ISSUE THREAD

**Issue by Exodia** [fouber/fis-parser-less#11]
不是很确定是不是less版本的问题

**Comment by zlzdp** [comment]
你试试这个https://github.com/fouber/fis-parser-less-2.x

**Comment by Exodia** [comment]
@dajbd 2.x我试了下，遇到了这个问题: https://github.com/fouber/fis-parser-less-2.x/issues/1

**Comment by Exodia** [comment]
@dajbd 谢谢，是我配置的selector搞错了，可以啦：）
