### ISSUE TITLE
什么时候考虑升级 less@2.2+?

### ISSUE THREAD

**Issue by DeyuanTan** [fouber/fis-parser-less#8]
什么时候考虑升级 less@2.2+?

**Comment by fouber** [comment]
@DeyuanTan 

发布了一个 `fis-parser-less-2.x` 插件，可以用这个

**Comment by DeyuanTan** [comment]
![image](https://cloud.githubusercontent.com/assets/8966624/7670309/89a386be-fcd2-11e4-8b9b-2fc30f1750ff.png) 谢谢
